#!/bin/bash
git_root=$(pwd -P 2>/dev/null || command pwd)
while [ ! -e "$git_root/.git" ]; do
        git_root=${git_root%/*}
        if [ "$git_root" = "" ]; then
                git_root=$PWD
                break;
        fi
done

docker run -it --rm --net=host -v "$HOME"/.gitconfig:/home/developer/.gitconfig -v "$git_root"/:/home/developer/workspace/ rodrigomiguele/git "$@"
